#!/bin/bash

WORKDIR="$( cd "$( dirname "$0" )" && pwd )"
cd "${WORKDIR}" && cd .. && cd skills

SKILLS_PATH="$( pwd )"


for skill in *
do
    if [ -d "$skill" ]
    then
        echo "Loading skill: ${skill} .."
        
        cp -r ${SKILLS_PATH}/${skill} ../../../../.mycroft/skills/
    fi
done
