#!/bin/bash

WORKDIR="$( cd "$( dirname "$0" )" && pwd )"
cd "${WORKDIR}" && cd ../skills

SKILLS_PATH="$( pwd )"
TARGET_SKILLS_PATH="$( cd ../../../../.mycroft/skills/ && pwd )"


for skill in *
do
    if [ -d "$skill" ]
    then
        echo "Loading skill: ${skill} .."
        
        rm -r ${TARGET_SKILLS_PATH}/${skill} >/dev/null
        
        cp -r ${SKILLS_PATH}/${skill} ${TARGET_SKILLS_PATH}
    fi
done
