#!/bin/bash

MYCROFT_PORT=8181

WORKDIR="$( cd "$( dirname "$0" )" && pwd )"
cd "${WORKDIR}"

MYCROFT_CONFIG_DIR="$( cd .. && cd .. && cd .. && pwd )"


source ./scripts/setup


echo "Starting mycroft.."

docker ps -a | grep mycroft >/dev/null
if [ $? -ne 1 ]
then
    echo "Container 'mycroft' already exists. Restarting.."
    
    docker restart mycroft
    exit 0
fi

docker run -d \
-v ${MYCROFT_CONFIG_DIR}/.mycroft/config:/root/.mycroft \
-v ${MYCROFT_CONFIG_DIR}/.mycroft/skills:/opt/mycroft/skills \
--device /dev/snd \
-e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
-v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native \
-v ~/.config/pulse/cookie:/root/.config/pulse/cookie \
-p ${MYCROFT_PORT}:8181 \
--name mycroft mycroftai/docker-mycroft

if [ $? -ne 0 ]
then
    echo "Unable to start container for mycroft."
    
    exit 1
fi

echo "Mycroft successfully started and listening on port: ${MYCROFT_PORT}"
